version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: formulaone_db
    environment:
      MYSQL_ROOT_PASSWORD: f1dbpassword
      MYSQL_DATABASE: formulaone
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: